//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WhiteSpaceRule.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="WhiteSpaceRule">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="Collapse"/>
 *     <enumeration value="Preserve"/>
 *     <enumeration value="Replace"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "WhiteSpaceRule")
@XmlEnum
public enum WhiteSpaceRule {


    /**
     * After the processing implied by the replace, contiguous sequences of Unicode hexadecimal #x20's are collapsed to a single #x20, and any #x20 at the start or end of the string is then removed.
     * 
     */
    @XmlEnumValue("Collapse")
    COLLAPSE("Collapse"),

    /**
     * No normalization is done, the value is not changed (this is the behavior required by XML for element content).
     * 
     */
    @XmlEnumValue("Preserve")
    PRESERVE("Preserve"),

    /**
     * All occurrences of Unicode hexadecimal #x9 (tab), #xA (line feed) and #xD (carriage return) are replaced with #x20 (space).
     * 
     */
    @XmlEnumValue("Replace")
    REPLACE("Replace");
    private final String value;

    WhiteSpaceRule(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WhiteSpaceRule fromValue(String v) {
        for (WhiteSpaceRule c: WhiteSpaceRule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
