//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CategoryRelationCode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>{@code
 * <simpleType name="CategoryRelationCode">
 *   <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     <enumeration value="Continuous"/>
 *     <enumeration value="Interval"/>
 *     <enumeration value="Nominal"/>
 *     <enumeration value="Ordinal"/>
 *     <enumeration value="Ratio"/>
 *   </restriction>
 * </simpleType>
 * }</pre>
 * 
 */
@XmlType(name = "CategoryRelationCode")
@XmlEnum
public enum CategoryRelationCode {


    /**
     * May be used to identify both interval and ratio classification levels, when more precise information is not available.
     * 
     */
    @XmlEnumValue("Continuous")
    CONTINUOUS("Continuous"),

    /**
     * The categories in the domain are in rank order and have a consistent interval between each category so that differences between arbitrary pairs of measurements can be meaningfully compared.
     * 
     */
    @XmlEnumValue("Interval")
    INTERVAL("Interval"),

    /**
     * A relationship of less than, or greater than, cannot be established among the included categories. This type of relationship is also called categorical or discrete.
     * 
     */
    @XmlEnumValue("Nominal")
    NOMINAL("Nominal"),

    /**
     * The categories in the domain have a rank order.
     * 
     */
    @XmlEnumValue("Ordinal")
    ORDINAL("Ordinal"),

    /**
     * The categories have all the features of interval measurement and also have meaningful ratios between arbitrary pairs of numbers.
     * 
     */
    @XmlEnumValue("Ratio")
    RATIO("Ratio");
    private final String value;

    CategoryRelationCode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CategoryRelationCode fromValue(String v) {
        for (CategoryRelationCode c: CategoryRelationCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
