//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition 
 *             ============ 
 *             Description of the relationships between and among categories within a collection.  
 *             
 *             Examples 
 *             ========== 
 *             The category of "student" might be described as having sub-types of "primary school student" and "high school student".  
 *             
 *             
 *             Explanatory notes 
 *             =================== 
 *             The category relation structure employs a set of category relations to describe the relationship among concepts. Each category relation is a one to many description of connections between categories. Together they might commonly describe relationships as complex as a hierarchy or graph. This is a kind of a concept structure restricted to categories (which are concepts). Allows for the specification of complex relationships among categories.
 * 
 * <p>Java class for CategoryRelationStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="CategoryRelationStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identifier" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Identifier" minOccurs="0"/>
 *         <element name="name" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ObjectName" maxOccurs="unbounded" minOccurs="0"/>
 *         <element name="purpose" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalString" minOccurs="0"/>
 *         <element name="semantics" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ControlledVocabularyEntry" minOccurs="0"/>
 *         <element name="specification" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}StructureSpecification" minOccurs="0"/>
 *         <element name="topology" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ControlledVocabularyEntry" minOccurs="0"/>
 *         <element name="totality" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}StructureExtent" minOccurs="0"/>
 *         <element name="CategoryRelationStructure_structures_CategorySet" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}AssociationReference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="CategorySet"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="CategoryRelationStructure_has_CategoryRelationship" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}AssociationReference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="CategoryRelationship"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CategoryRelationStructure", propOrder = {
    "identifier",
    "name",
    "purpose",
    "semantics",
    "specification",
    "topology",
    "totality",
    "categoryRelationStructureStructuresCategorySet",
    "categoryRelationStructureHasCategoryRelationship"
})
public class CategoryRelationStructure {

    protected Identifier identifier;
    protected List<ObjectName> name;
    protected InternationalString purpose;
    protected ControlledVocabularyEntry semantics;
    protected StructureSpecification specification;
    protected ControlledVocabularyEntry topology;
    @XmlSchemaType(name = "NMTOKEN")
    protected StructureExtent totality;
    @XmlElement(name = "CategoryRelationStructure_structures_CategorySet")
    protected CategoryRelationStructure.CategoryRelationStructureStructuresCategorySet categoryRelationStructureStructuresCategorySet;
    @XmlElement(name = "CategoryRelationStructure_has_CategoryRelationship")
    protected List<CategoryRelationStructure.CategoryRelationStructureHasCategoryRelationship> categoryRelationStructureHasCategoryRelationship;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectName }
     * 
     * 
     * @return
     *     The value of the name property.
     */
    public List<ObjectName> getName() {
        if (name == null) {
            name = new ArrayList<>();
        }
        return this.name;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalString }
     *     
     */
    public InternationalString getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalString }
     *     
     */
    public void setPurpose(InternationalString value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public ControlledVocabularyEntry getSemantics() {
        return semantics;
    }

    /**
     * Sets the value of the semantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public void setSemantics(ControlledVocabularyEntry value) {
        this.semantics = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link StructureSpecification }
     *     
     */
    public StructureSpecification getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureSpecification }
     *     
     */
    public void setSpecification(StructureSpecification value) {
        this.specification = value;
    }

    /**
     * Gets the value of the topology property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public ControlledVocabularyEntry getTopology() {
        return topology;
    }

    /**
     * Sets the value of the topology property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public void setTopology(ControlledVocabularyEntry value) {
        this.topology = value;
    }

    /**
     * Gets the value of the totality property.
     * 
     * @return
     *     possible object is
     *     {@link StructureExtent }
     *     
     */
    public StructureExtent getTotality() {
        return totality;
    }

    /**
     * Sets the value of the totality property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureExtent }
     *     
     */
    public void setTotality(StructureExtent value) {
        this.totality = value;
    }

    /**
     * Gets the value of the categoryRelationStructureStructuresCategorySet property.
     * 
     * @return
     *     possible object is
     *     {@link CategoryRelationStructure.CategoryRelationStructureStructuresCategorySet }
     *     
     */
    public CategoryRelationStructure.CategoryRelationStructureStructuresCategorySet getCategoryRelationStructureStructuresCategorySet() {
        return categoryRelationStructureStructuresCategorySet;
    }

    /**
     * Sets the value of the categoryRelationStructureStructuresCategorySet property.
     * 
     * @param value
     *     allowed object is
     *     {@link CategoryRelationStructure.CategoryRelationStructureStructuresCategorySet }
     *     
     */
    public void setCategoryRelationStructureStructuresCategorySet(CategoryRelationStructure.CategoryRelationStructureStructuresCategorySet value) {
        this.categoryRelationStructureStructuresCategorySet = value;
    }

    /**
     * Gets the value of the categoryRelationStructureHasCategoryRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the categoryRelationStructureHasCategoryRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryRelationStructureHasCategoryRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CategoryRelationStructure.CategoryRelationStructureHasCategoryRelationship }
     * 
     * 
     * @return
     *     The value of the categoryRelationStructureHasCategoryRelationship property.
     */
    public List<CategoryRelationStructure.CategoryRelationStructureHasCategoryRelationship> getCategoryRelationStructureHasCategoryRelationship() {
        if (categoryRelationStructureHasCategoryRelationship == null) {
            categoryRelationStructureHasCategoryRelationship = new ArrayList<>();
        }
        return this.categoryRelationStructureHasCategoryRelationship;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}AssociationReference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="CategoryRelationship"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CategoryRelationStructureHasCategoryRelationship
        extends AssociationReference
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}AssociationReference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="CategorySet"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class CategoryRelationStructureStructuresCategorySet
        extends AssociationReference
    {


    }

}
