//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition
 *             ==========
 *             Description of unit-record ("wide") data sets, where each row in the data set provides the same group of values for variables all relating to a single unit.
 *             
 *             Examples
 *             ========
 *             A simple spreadsheet. Commonly the first row of the table will contain variable names or descriptions.
 *             
 *             The following CSV file has a rectangular layout and would import into a simple table in a spreadsheet::
 *             
 *                PersonId,AgeYr,HeightCm
 *                1,22,183,
 *                2,45,175,
 *             
 *             Explanatory notes
 *             =================
 *             This is the classic rectangular data table used by most statistical packages, with rows/cases/observations and columns/variables/measurements. Each cell (DataPoint) in the table is the intersection of a Unit (row) and an InstanceVariable. Each logical column will contain data relating to the values for a single variable.
 * 
 * <p>Java class for UnitSegmentLayout complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="UnitSegmentLayout">
 *   <complexContent>
 *     <extension base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}PhysicalSegmentLayout">
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnitSegmentLayout")
public class UnitSegmentLayout
    extends PhysicalSegmentLayout
{


}
