//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition 
 *             ============ 
 *             Role given to a represented variable in the context of a data structure to qualify observations or provide other types of supplementary information.  
 *             
 *             Examples 
 *             ========== 
 *             The publication status of an observation (e.g. provisional, final, revised).
 * 
 * <p>Java class for AttributeComponent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="AttributeComponent">
 *   <complexContent>
 *     <extension base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}DataStructureComponent">
 *       <sequence>
 *         <element name="AttributeComponent_qualifies_DataStructureComponent" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="AttributeComponent"/>
 *                         <enumeration value="ContextualComponent"/>
 *                         <enumeration value="DataStructure"/>
 *                         <enumeration value="DataStructureComponent"/>
 *                         <enumeration value="DimensionComponent"/>
 *                         <enumeration value="DimensionalDataStructure"/>
 *                         <enumeration value="IdentifierComponent"/>
 *                         <enumeration value="KeyValueStructure"/>
 *                         <enumeration value="LongDataStructure"/>
 *                         <enumeration value="MeasureComponent"/>
 *                         <enumeration value="QualifiedMeasure"/>
 *                         <enumeration value="SyntheticIdComponent"/>
 *                         <enumeration value="VariableDescriptorComponent"/>
 *                         <enumeration value="VariableValueComponent"/>
 *                         <enumeration value="WideDataStructure"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AttributeComponent", propOrder = {
    "attributeComponentQualifiesDataStructureComponent"
})
public class AttributeComponent
    extends DataStructureComponent
{

    @XmlElement(name = "AttributeComponent_qualifies_DataStructureComponent")
    protected List<AttributeComponent.AttributeComponentQualifiesDataStructureComponent> attributeComponentQualifiesDataStructureComponent;

    /**
     * Gets the value of the attributeComponentQualifiesDataStructureComponent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the attributeComponentQualifiesDataStructureComponent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeComponentQualifiesDataStructureComponent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeComponent.AttributeComponentQualifiesDataStructureComponent }
     * 
     * 
     * @return
     *     The value of the attributeComponentQualifiesDataStructureComponent property.
     */
    public List<AttributeComponent.AttributeComponentQualifiesDataStructureComponent> getAttributeComponentQualifiesDataStructureComponent() {
        if (attributeComponentQualifiesDataStructureComponent == null) {
            attributeComponentQualifiesDataStructureComponent = new ArrayList<>();
        }
        return this.attributeComponentQualifiesDataStructureComponent;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="AttributeComponent"/>
     *               <enumeration value="ContextualComponent"/>
     *               <enumeration value="DataStructure"/>
     *               <enumeration value="DataStructureComponent"/>
     *               <enumeration value="DimensionComponent"/>
     *               <enumeration value="DimensionalDataStructure"/>
     *               <enumeration value="IdentifierComponent"/>
     *               <enumeration value="KeyValueStructure"/>
     *               <enumeration value="LongDataStructure"/>
     *               <enumeration value="MeasureComponent"/>
     *               <enumeration value="QualifiedMeasure"/>
     *               <enumeration value="SyntheticIdComponent"/>
     *               <enumeration value="VariableDescriptorComponent"/>
     *               <enumeration value="VariableValueComponent"/>
     *               <enumeration value="WideDataStructure"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class AttributeComponentQualifiesDataStructureComponent
        extends Reference
    {


    }

}
