//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition
 *             ============
 *             Single data instance that is part of a dimensional key. 
 *             
 *             Examples
 *             ==========
 *             The "Ontario" string in a dimensional dataset where data points are identified by Province and other dimensions.
 * 
 * <p>Java class for DimensionalKeyMember complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="DimensionalKeyMember">
 *   <complexContent>
 *     <extension base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}KeyMember">
 *       <sequence>
 *         <element name="DimensionalKeyMember_hasValueFrom_CodeList">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="CodeList"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DimensionalKeyMember", propOrder = {
    "dimensionalKeyMemberHasValueFromCodeList"
})
public class DimensionalKeyMember
    extends KeyMember
{

    @XmlElement(name = "DimensionalKeyMember_hasValueFrom_CodeList", required = true)
    protected DimensionalKeyMember.DimensionalKeyMemberHasValueFromCodeList dimensionalKeyMemberHasValueFromCodeList;

    /**
     * Gets the value of the dimensionalKeyMemberHasValueFromCodeList property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionalKeyMember.DimensionalKeyMemberHasValueFromCodeList }
     *     
     */
    public DimensionalKeyMember.DimensionalKeyMemberHasValueFromCodeList getDimensionalKeyMemberHasValueFromCodeList() {
        return dimensionalKeyMemberHasValueFromCodeList;
    }

    /**
     * Sets the value of the dimensionalKeyMemberHasValueFromCodeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionalKeyMember.DimensionalKeyMemberHasValueFromCodeList }
     *     
     */
    public void setDimensionalKeyMemberHasValueFromCodeList(DimensionalKeyMember.DimensionalKeyMemberHasValueFromCodeList value) {
        this.dimensionalKeyMemberHasValueFromCodeList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="CodeList"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DimensionalKeyMemberHasValueFromCodeList
        extends Reference
    {


    }

}
