//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition
 *             ============
 *             Identifies the unit of interest, either a statistical unit or a population, via identifier or dimension components, respectively, plus an optional contextual component. 
 *             If neither identifier nor dimension components are present, then a synthetic id component is used. 
 *             
 *             Examples
 *             ==========
 *             The string "income_distribution:male:Ontario:married" in a dimensional key-value datastore, where instance key members are defined by context plus Sex, Province and Marital Status dimensions.
 * 
 * <p>Java class for MainKeyMember complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="MainKeyMember">
 *   <complexContent>
 *     <extension base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}KeyMember">
 *       <sequence>
 *         <element name="MainKeyMember_hasValueFrom_SubstantiveValueDomain" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="DescriptorValueDomain"/>
 *                         <enumeration value="SubstantiveValueDomain"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MainKeyMember", propOrder = {
    "mainKeyMemberHasValueFromSubstantiveValueDomain"
})
public class MainKeyMember
    extends KeyMember
{

    @XmlElement(name = "MainKeyMember_hasValueFrom_SubstantiveValueDomain")
    protected MainKeyMember.MainKeyMemberHasValueFromSubstantiveValueDomain mainKeyMemberHasValueFromSubstantiveValueDomain;

    /**
     * Gets the value of the mainKeyMemberHasValueFromSubstantiveValueDomain property.
     * 
     * @return
     *     possible object is
     *     {@link MainKeyMember.MainKeyMemberHasValueFromSubstantiveValueDomain }
     *     
     */
    public MainKeyMember.MainKeyMemberHasValueFromSubstantiveValueDomain getMainKeyMemberHasValueFromSubstantiveValueDomain() {
        return mainKeyMemberHasValueFromSubstantiveValueDomain;
    }

    /**
     * Sets the value of the mainKeyMemberHasValueFromSubstantiveValueDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainKeyMember.MainKeyMemberHasValueFromSubstantiveValueDomain }
     *     
     */
    public void setMainKeyMemberHasValueFromSubstantiveValueDomain(MainKeyMember.MainKeyMemberHasValueFromSubstantiveValueDomain value) {
        this.mainKeyMemberHasValueFromSubstantiveValueDomain = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="DescriptorValueDomain"/>
     *               <enumeration value="SubstantiveValueDomain"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MainKeyMemberHasValueFromSubstantiveValueDomain
        extends Reference
    {


    }

}
