//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition 
 *             ============ 
 *             Ordering for physical record segments, which map to a logical record.
 *             
 *             Explanatory notes 
 *             =================== 
 *             The same logical record layout may be the source member in several adjacency lists. This can happen when physical record segments are also population specific. In this instance each adjacency list associated with a logical record layout is associated with a different population.
 * 
 * <p>Java class for PhysicalDataSetStructure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="PhysicalDataSetStructure">
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="identifier" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Identifier" minOccurs="0"/>
 *         <element name="name" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ObjectName" minOccurs="0"/>
 *         <element name="purpose" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalString" minOccurs="0"/>
 *         <element name="semantics" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ControlledVocabularyEntry" minOccurs="0"/>
 *         <element name="specification" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}StructureSpecification" minOccurs="0"/>
 *         <element name="topology" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}ControlledVocabularyEntry" minOccurs="0"/>
 *         <element name="totality" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}StructureExtent" minOccurs="0"/>
 *         <element name="PhysicalDataSetStructure_structures_PhysicalDataSet" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="PhysicalDataSet"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *         <element name="PhysicalDataSetStructure_has_PhysicalRecordSegmentRelationship" maxOccurs="unbounded" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="PhysicalRecordSegmentRelationship"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicalDataSetStructure", propOrder = {
    "identifier",
    "name",
    "purpose",
    "semantics",
    "specification",
    "topology",
    "totality",
    "physicalDataSetStructureStructuresPhysicalDataSet",
    "physicalDataSetStructureHasPhysicalRecordSegmentRelationship"
})
public class PhysicalDataSetStructure {

    protected Identifier identifier;
    protected ObjectName name;
    protected InternationalString purpose;
    protected ControlledVocabularyEntry semantics;
    protected StructureSpecification specification;
    protected ControlledVocabularyEntry topology;
    @XmlSchemaType(name = "NMTOKEN")
    protected StructureExtent totality;
    @XmlElement(name = "PhysicalDataSetStructure_structures_PhysicalDataSet")
    protected PhysicalDataSetStructure.PhysicalDataSetStructureStructuresPhysicalDataSet physicalDataSetStructureStructuresPhysicalDataSet;
    @XmlElement(name = "PhysicalDataSetStructure_has_PhysicalRecordSegmentRelationship")
    protected List<PhysicalDataSetStructure.PhysicalDataSetStructureHasPhysicalRecordSegmentRelationship> physicalDataSetStructureHasPhysicalRecordSegmentRelationship;

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setIdentifier(Identifier value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ObjectName }
     *     
     */
    public ObjectName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ObjectName }
     *     
     */
    public void setName(ObjectName value) {
        this.name = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalString }
     *     
     */
    public InternationalString getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalString }
     *     
     */
    public void setPurpose(InternationalString value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the semantics property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public ControlledVocabularyEntry getSemantics() {
        return semantics;
    }

    /**
     * Sets the value of the semantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public void setSemantics(ControlledVocabularyEntry value) {
        this.semantics = value;
    }

    /**
     * Gets the value of the specification property.
     * 
     * @return
     *     possible object is
     *     {@link StructureSpecification }
     *     
     */
    public StructureSpecification getSpecification() {
        return specification;
    }

    /**
     * Sets the value of the specification property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureSpecification }
     *     
     */
    public void setSpecification(StructureSpecification value) {
        this.specification = value;
    }

    /**
     * Gets the value of the topology property.
     * 
     * @return
     *     possible object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public ControlledVocabularyEntry getTopology() {
        return topology;
    }

    /**
     * Sets the value of the topology property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlledVocabularyEntry }
     *     
     */
    public void setTopology(ControlledVocabularyEntry value) {
        this.topology = value;
    }

    /**
     * Gets the value of the totality property.
     * 
     * @return
     *     possible object is
     *     {@link StructureExtent }
     *     
     */
    public StructureExtent getTotality() {
        return totality;
    }

    /**
     * Sets the value of the totality property.
     * 
     * @param value
     *     allowed object is
     *     {@link StructureExtent }
     *     
     */
    public void setTotality(StructureExtent value) {
        this.totality = value;
    }

    /**
     * Gets the value of the physicalDataSetStructureStructuresPhysicalDataSet property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalDataSetStructure.PhysicalDataSetStructureStructuresPhysicalDataSet }
     *     
     */
    public PhysicalDataSetStructure.PhysicalDataSetStructureStructuresPhysicalDataSet getPhysicalDataSetStructureStructuresPhysicalDataSet() {
        return physicalDataSetStructureStructuresPhysicalDataSet;
    }

    /**
     * Sets the value of the physicalDataSetStructureStructuresPhysicalDataSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalDataSetStructure.PhysicalDataSetStructureStructuresPhysicalDataSet }
     *     
     */
    public void setPhysicalDataSetStructureStructuresPhysicalDataSet(PhysicalDataSetStructure.PhysicalDataSetStructureStructuresPhysicalDataSet value) {
        this.physicalDataSetStructureStructuresPhysicalDataSet = value;
    }

    /**
     * Gets the value of the physicalDataSetStructureHasPhysicalRecordSegmentRelationship property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a {@code set} method for the physicalDataSetStructureHasPhysicalRecordSegmentRelationship property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhysicalDataSetStructureHasPhysicalRecordSegmentRelationship().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhysicalDataSetStructure.PhysicalDataSetStructureHasPhysicalRecordSegmentRelationship }
     * 
     * 
     * @return
     *     The value of the physicalDataSetStructureHasPhysicalRecordSegmentRelationship property.
     */
    public List<PhysicalDataSetStructure.PhysicalDataSetStructureHasPhysicalRecordSegmentRelationship> getPhysicalDataSetStructureHasPhysicalRecordSegmentRelationship() {
        if (physicalDataSetStructureHasPhysicalRecordSegmentRelationship == null) {
            physicalDataSetStructureHasPhysicalRecordSegmentRelationship = new ArrayList<>();
        }
        return this.physicalDataSetStructureHasPhysicalRecordSegmentRelationship;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="PhysicalRecordSegmentRelationship"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PhysicalDataSetStructureHasPhysicalRecordSegmentRelationship
        extends Reference
    {


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="PhysicalDataSet"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PhysicalDataSetStructureStructuresPhysicalDataSet
        extends Reference
    {


    }

}
