//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package org.ddialliance.specification.ddi_cdi._1_0.xmlschema;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Definition
 *             ============
 *             A datum that can be qualified by a revision.
 *             
 *             Examples
 *             ==========
 *             The April datum for Income revised in June.
 * 
 * <p>Java class for RevisableDatum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>{@code
 * <complexType name="RevisableDatum">
 *   <complexContent>
 *     <extension base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Datum">
 *       <sequence>
 *         <element name="vintage" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         <element name="RevisableDatum_correspondsTo_Revision" minOccurs="0">
 *           <complexType>
 *             <complexContent>
 *               <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
 *                 <sequence>
 *                   <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
 *                   <element name="validType" maxOccurs="unbounded" minOccurs="0">
 *                     <simpleType>
 *                       <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         <enumeration value="Revision"/>
 *                       </restriction>
 *                     </simpleType>
 *                   </element>
 *                 </sequence>
 *                 <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
 *               </restriction>
 *             </complexContent>
 *           </complexType>
 *         </element>
 *       </sequence>
 *     </extension>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RevisableDatum", propOrder = {
    "vintage",
    "revisableDatumCorrespondsToRevision"
})
public class RevisableDatum
    extends Datum
{

    @XmlElement(required = true)
    protected BigInteger vintage;
    @XmlElement(name = "RevisableDatum_correspondsTo_Revision")
    protected RevisableDatum.RevisableDatumCorrespondsToRevision revisableDatumCorrespondsToRevision;

    /**
     * Gets the value of the vintage property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVintage() {
        return vintage;
    }

    /**
     * Sets the value of the vintage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVintage(BigInteger value) {
        this.vintage = value;
    }

    /**
     * Gets the value of the revisableDatumCorrespondsToRevision property.
     * 
     * @return
     *     possible object is
     *     {@link RevisableDatum.RevisableDatumCorrespondsToRevision }
     *     
     */
    public RevisableDatum.RevisableDatumCorrespondsToRevision getRevisableDatumCorrespondsToRevision() {
        return revisableDatumCorrespondsToRevision;
    }

    /**
     * Sets the value of the revisableDatumCorrespondsToRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisableDatum.RevisableDatumCorrespondsToRevision }
     *     
     */
    public void setRevisableDatumCorrespondsToRevision(RevisableDatum.RevisableDatumCorrespondsToRevision value) {
        this.revisableDatumCorrespondsToRevision = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>{@code
     * <complexType>
     *   <complexContent>
     *     <restriction base="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}Reference">
     *       <sequence>
     *         <element name="ddiReference" type="{http://ddialliance.org/Specification/DDI-CDI/1.0/XMLSchema/}InternationalRegistrationDataIdentifier" minOccurs="0"/>
     *         <element name="validType" maxOccurs="unbounded" minOccurs="0">
     *           <simpleType>
     *             <restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               <enumeration value="Revision"/>
     *             </restriction>
     *           </simpleType>
     *         </element>
     *       </sequence>
     *       <attribute name="isAssociationReference" type="{http://www.w3.org/2001/XMLSchema}boolean" fixed="true" />
     *     </restriction>
     *   </complexContent>
     * </complexType>
     * }</pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class RevisableDatumCorrespondsToRevision
        extends Reference
    {


    }

}
